export const environment = {
  production: false,
  env: 'development',
  BaseUrl: 'https://dummyjson.com/',
  ProductUrl: '/products',
  ProductCategoryUrl: '/products/categories',
  PostUrl: '/posts',
  RecipeUrl: '/recipes',
  QuoteUrl: '/quotes',
  AuthUrl: '/auth',
  LoginUrl: '/auth/login',
  RefreshTokenUrl: 'auth/refresh',
  CurrentUserUrl: '/auth/me',
  loaderDelayMs: 0,
};
